[package]
name = "rusttest"
authors = ["Jack Kozik <jackkozik@email.com>"]
description = ""
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
spin-sdk = { git = "https://github.com/fermyon/spin", branch = "main" }

[workspace]
